In [1]:
#Imports
import os
import pandas as pd
import numpy as np

In [2]:
#Read CSV
ufo_data = pd.read_csv('../UFO_data.csv')

In [3]:
#Remove American Territories - US States Only
ufo_data = ufo_data.drop(ufo_data[ufo_data['State'] == "American Samoa"].index)

In [4]:
ufo_data

,Date,City,State,Country,Shape,Duration,Summary,Posted,Images,ReportNum,Location,Latitude,Longitude
0,2022-07-31 21:59:00,West Lafayette,OH,USA,Light,4 minutes,Bright circle light moving through sky.,9/9/22,Yes,1,"West Lafayette, OH",40.275349,-81.750960
1,2022-07-31 21:45:00,Burr Ridge,IL,USA,Other,NaN,"Strange red, blue and black craft in the sky a...",9/9/22,Yes,2,"Burr Ridge, IL",41.748920,-87.918392
2,2022-07-31 21:15:00,Conway,SC,USA,Circle,Less than a minute,Round bright white light go in a straight line...,9/9/22,NaN,3,"Conway, SC",33.836003,-79.047814
3,2022-07-31 21:11:00,Keyser,WV,USA,Light,2 minutes,Saw an orb that interacted with me.,9/9/22,NaN,4,"Keyser, WV",39.440928,-78.973916
4,2022-07-31 20:43:00,gressham,OR,USA,Unknown,less than a minute,A single soft red light that pulsed three time...,9/9/22,NaN,5,"gressham, OR",45.504472,-122.435666
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2055,2022-12-01 18:10:00,Blakeslee,OH,USA,Sphere,5 minutes,Bright spherical object moving linear west to ...,12/22/22,Yes,2126,"Blakeslee, OH",41.524217,-84.730233
2056,2022-12-01 18:00:00,Snowflake,AZ,USA,Triangle,2 minutes,I grew up on a 40 acre parcel of land with thr...,12/22/22,NaN,2127,"Snowflake, AZ",34.513370,-110.078449
2057,2022-12-01 14:10:00,El paso,TX,USA,Oval,Ten minutes,It appeared out of nowhere & slowly moved acro...,12/22/22,NaN,2129,"El paso, TX",31.761878,-106.485022
2058,2022-12-01 06:20:00,CHARLESTOWN,IN,USA,Light,2 to 3 minutes,Bright object was seen arriving and silently h...,12/22/22,Yes,2130,"CHARLESTOWN, IN",38.453120,-85.670241
2059,2022-12-01 03:59:00,Mansfield,TX,USA,Changing,60 seconds,Looked like a drone but moved way too fast the...,12/22/22,NaN,2131,"Mansfield, TX",32.563192,-97.141677

In [6]:
states = ufo_data.groupby(['State']).count()
states

,Date,City,Country,Shape,Duration,Summary,Posted,Images,ReportNum,Location,Latitude,Longitude
State,,,,,,,,,,,,
AK,3,3,3,2,3,3,3,3,3,3,3,3
AL,28,28,28,28,28,28,28,10,28,28,28,28
AR,18,18,18,18,17,18,18,5,18,18,18,18
AZ,64,64,64,62,62,64,64,23,64,64,64,64
CA,203,203,203,202,193,203,203,41,203,203,203,203
CO,58,58,58,58,51,58,58,13,58,58,58,58
CT,35,35,35,32,32,35,35,12,35,35,35,35
DC,3,3,3,3,3,3,3,2,3,3,3,3
DE,11,11,11,11,11,11,11,3,11,11,11,11
FL,152,152,152,151,149,152,152,42,152,152,152,152
GA,35,35,35,35,34,35,35,9,35,35,35,35
HI,5,5,5,5,5,5,5,1,5,5,5,5
IA,14,14,14,14,14,14,14,4,14,14,13,13
ID,24,24,24,24,23,24,24,7,24,24,24,24
IL,58,58,58,58,53,58,58,18,58,58,58,58
IN,38,38,38,37,37,38,38,7,38,38,38,38
KS,12,12,12,12,12,12,12,5,12,12,11,11
KY,27,27,27,27,25,27,27,7,27,27,27,27
LA,21,21,21,20,20,21,21,8,21,21,21,21
MA,53,53,53,53,51,53,53,8,53,53,53,53
MD,31,31,31,31,30,31,31,8,31,31,31,31
ME,25,25,25,25,24,25,25,6,25,25,25,25
MI,50,50,50,48,43,50,50,16,50,50,50,50
MN,33,33,33,33,32,33,33,15,33,33,33,33
MO,42,42,42,41,41,42,42,6,42,42,42,42
MS,12,12,12,11,12,12,12,2,12,12,12,12
MT,18,18,18,17,18,18,18,8,18,18,18,18
NC,67,67,67,66,66,67,67,21,67,67,67,67
ND,2,2,2,2,2,2,2,1,2,2,2,2
NE,8,8,8,8,8,8,8,2,8,8,7,7
NH,24,24,24,23,23,24,24,8,24,24,24,24
NJ,54,54,54,54,54,54,54,20,54,54,54,54
NM,27,27,27,27,26,27,27,13,27,27,27,27
NV,26,26,26,25,26,26,26,7,26,26,26,26
NY,103,103,103,100,100,103,103,30,103,103,103,103
OH,75,75,75,74,71,75,75,24,75,75,74,74
OK,26,26,26,25,24,26,26,3,26,26,26,26
ON,1,1,1,1,1,1,1,0,1,1,1,1
OR,51,51,51,49,50,51,51,16,51,51,51,51
PA,113,113,113,113,108,113,113,37,113,113,112,112
RI,12,12,12,12,12,12,12,4,12,12,12,12
SC,30,30,30,30,28,30,30,10,30,30,30,30
SD,6,6,6,6,6,6,6,2,6,6,6,6
TN,37,37,37,37,35,37,37,8,37,37,36,36
TX,89,89,89,88,85,89,89,31,89,89,89,89
UT,22,22,22,22,21,22,22,8,22,22,22,22
VA,42,42,42,41,41,42,42,11,42,42,42,42
VT,16,16,16,16,16,16,16,3,16,16,16,16
WA,82,82,82,82,81,82,82,26,82,82,82,82
WI,49,49,49,48,48,49,49,11,49,49,49,49
WV,14,14,14,14,14,14,14,4,14,14,14,14
WY,10,10,10,9,10,10,10,3,10,10,10,10

In [30]:
#Summary of UFO Sightings by State
print("Count of UFO Sightings by State:")
states = ufo_data.groupby(['State']).size().to_frame(name = 'Sightings').reset_index()
states

Count of UFO Sightings by State:

   State  Sightings
0     AK          3
1     AL         28
2     AR         18
3     AZ         64
4     CA        203
5     CO         58
6     CT         35
7     DC          3
8     DE         11
9     FL        152
10    GA         35
11    HI          5
12    IA         14
13    ID         24
14    IL         58
15    IN         38
16    KS         12
17    KY         27
18    LA         21
19    MA         53
20    MD         31
21    ME         25
22    MI         50
23    MN         33
24    MO         42
25    MS         12
26    MT         18
27    NC         67
28    ND          2
29    NE          8
30    NH         24
31    NJ         54
32    NM         27
33    NV         26
34    NY        103
35    OH         75
36    OK         26
37    ON          1
38    OR         51
39    PA        113
40    RI         12
41    SC         30
42    SD          6
43    TN         37
44    TX         89
45    UT         22
46    VA         42
47    VT         16
48    WA         82
49    WI         49
50    WV         14
51    WY         10

In [11]:
ufo_state = ufo_data.groupby('State').count()['City']

In [13]:
# write to csv file
states.to_csv('sightings_state.csv')